### ISSUE TITLE
1강 오타 제보드립니다.

### ISSUE THREAD

**Issue by Gyubin** [insurgent92/CS231N_17_KOR_SUB#2]
아래 두 부분에서 오타있습니다. 번역 감사합니다. 😄 👍 

- movataion -> motivation
- 받아드리는지 -> 받아들이는지

```
226
00:29:44,160 --> 00:29:52,440
우리에게는 두 가지 movataion이 있었습니다. 하나는
이 세상의 모든 것들을 인식하고 싶다는 것이고

...

379
00:48:34,564 --> 00:48:37,912
이를 미루어 우리는 사람들이 이 장면을 어떻게 
받아드리는지 이해할 수 있습니다.
```

**Comment by visionNoob** [comment]
안녕하세요! 신경 써주셔서 감사합니다. 오타 찾아내는 작업이 가장 힘든데
이렇게 도와주시니 정말 감사합니다  초벌 번역 상태라서 오타 및 오역이 많습니다.
다만 제가 2회~3회 정도 지속적으로 업데이트 & 수정 할 예정입니다. ㅎㅎ 감사합니다!
