### ISSUE TITLE
Lecture 3 한국어 번역 오탈자

### ISSUE THREAD

**Issue by Sjisoo** [insurgent92/CS231N_17_KOR_SUB#29]
[line73]
Pizza -> Piazza

[line341,751,770,774,825]
Flog -> Frog

**Comment by Sjisoo** [comment]
[line530]
SVM, sopport vector machine을 -> SVM(Support Vector Machine)

**Comment by visionNoob** [comment]
@Sjisoo 제보 감사합니다!

**Comment by visionNoob** [comment]
@Sjisoo 혹시 직접 PR 날려주실 수 있으신가요?
